use crate::core::volkiwithstds::collections::ToString;
use crate::core::volkiwithstds::collections::{String, Vec};
/// Parse Cargo.lock `[[package]]` entries into (name, version) pairs.
pub fn parse_cargo_lock_packages(content: &str) -> Vec<(String, String)> {
    let mut packages = Vec::new();
    let mut current_name: Option<String> = None;
    let mut current_version: Option<String> = None;

    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed == "[[package]]" {
            if let (Some(name), Some(version)) = (current_name.take(), current_version.take()) {
                packages.push((name, version));
            }
            current_name = None;
            current_version = None;
            continue;
        }

        if let Some(val) = extract_toml_line_value(trimmed, "name") {
            current_name = Some(val);
        } else if let Some(val) = extract_toml_line_value(trimmed, "version") {
            current_version = Some(val);
        }
    }

    // Flush last entry
    if let (Some(name), Some(version)) = (current_name, current_version) {
        packages.push((name, version));
    }

    packages
}

/// Extract a string value from a `key = "value"` TOML line.
pub fn extract_toml_string_value(content: &str, key: &str) -> Option<String> {
    let prefix = crate::vformat!("{key} = ");
    for line in content.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix(prefix.as_str()) {
            let rest = rest.trim();
            if rest.starts_with("\"") && rest.ends_with('"') && rest.len() >= 2 {
                return Some(rest[1..rest.len() - 1].to_vstring());
            }
        }
    }
    None
}

fn extract_toml_line_value(line: &str, key: &str) -> Option<String> {
    let prefix = crate::vformat!("{key} = ");
    if let Some(rest) = line.strip_prefix(prefix.as_str()) {
        let rest = rest.trim();
        if rest.starts_with("\"") && rest.ends_with('"') && rest.len() >= 2 {
            return Some(rest[1..rest.len() - 1].to_vstring());
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    // --- parse_cargo_lock_packages ---

    #[test]
    fn cargo_lock_empty() {
        assert!(parse_cargo_lock_packages("").is_empty());
    }

    #[test]
    fn cargo_lock_single_package() {
        let content = r#"[[package]]
name = "serde"
version = "1.0.200"
"#;
        let pkgs = parse_cargo_lock_packages(content);
        assert_eq!(pkgs.len(), 1);
        assert_eq!(pkgs[0], (crate::vstr!("serde"), crate::vstr!("1.0.200")));
    }

    #[test]
    fn cargo_lock_multiple_packages() {
        let content = r#"[[package]]
name = "serde"
version = "1.0.200"

[[package]]
name = "tokio"
version = "1.37.0"
"#;
        let pkgs = parse_cargo_lock_packages(content);
        assert_eq!(pkgs.len(), 2);
        assert_eq!(pkgs[0].0, "serde");
        assert_eq!(pkgs[1].0, "tokio");
    }

    #[test]
    fn cargo_lock_extra_fields_ignored() {
        let content = r#"[[package]]
name = "serde"
version = "1.0.200"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abc123"
"#;
        let pkgs = parse_cargo_lock_packages(content);
        assert_eq!(pkgs.len(), 1);
        assert_eq!(pkgs[0], (crate::vstr!("serde"), crate::vstr!("1.0.200")));
    }

    #[test]
    fn cargo_lock_missing_name_skipped() {
        let content = r#"[[package]]
version = "1.0.0"

[[package]]
name = "valid"
version = "2.0.0"
"#;
        let pkgs = parse_cargo_lock_packages(content);
        assert_eq!(pkgs.len(), 1);
        assert_eq!(pkgs[0].0, "valid");
    }

    #[test]
    fn cargo_lock_missing_version_skipped() {
        let content = r#"[[package]]
name = "noversion"

[[package]]
name = "valid"
version = "2.0.0"
"#;
        let pkgs = parse_cargo_lock_packages(content);
        assert_eq!(pkgs.len(), 1);
        assert_eq!(pkgs[0].0, "valid");
    }

    #[test]
    fn cargo_lock_real_format() {
        let content = r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "aho-corasick"
version = "1.1.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abc"
dependencies = [
 "memchr",
]

[[package]]
name = "memchr"
version = "2.7.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
"#;
        let pkgs = parse_cargo_lock_packages(content);
        assert_eq!(pkgs.len(), 2);
        assert_eq!(pkgs[0].0, "aho-corasick");
        assert_eq!(pkgs[1].0, "memchr");
    }

    #[test]
    fn cargo_lock_last_entry_flushed() {
        // Ensure the last entry without a trailing [[package]] is included
        let content = "[[package]]\nname = \"last\"\nversion = \"1.0.0\"\n";
        let pkgs = parse_cargo_lock_packages(content);
        assert_eq!(pkgs.len(), 1);
        assert_eq!(pkgs[0].0, "last");
    }

    // --- extract_toml_string_value ---

    #[test]
    fn toml_string_simple() {
        let content = "name = \"hello\"";
        assert_eq!(
            extract_toml_string_value(content, "name"),
            Some(crate::vstr!("hello"))
        );
    }

    #[test]
    fn toml_string_with_spaces() {
        let content = "  name = \"hello\"  ";
        assert_eq!(
            extract_toml_string_value(content, "name"),
            Some(crate::vstr!("hello"))
        );
    }

    #[test]
    fn toml_string_missing_key() {
        let content = "other = \"val\"";
        assert_eq!(extract_toml_string_value(content, "name"), None);
    }

    #[test]
    fn toml_string_unquoted_value() {
        let content = "name = hello";
        assert_eq!(extract_toml_string_value(content, "name"), None);
    }

    #[test]
    fn toml_string_first_match_wins() {
        let content = "name = \"first\"\nname = \"second\"";
        assert_eq!(
            extract_toml_string_value(content, "name"),
            Some(crate::vstr!("first"))
        );
    }

    #[test]
    fn toml_string_empty_value() {
        let content = "name = \"\"";
        assert_eq!(
            extract_toml_string_value(content, "name"),
            Some(crate::vstr!(""))
        );
    }

    #[test]
    fn toml_string_license_field() {
        let content = "[package]\nname = \"mylib\"\nversion = \"0.1.0\"\nlicense = \"MIT\"";
        assert_eq!(
            extract_toml_string_value(content, "license"),
            Some(crate::vstr!("MIT"))
        );
    }
}
